### ISSUE TITLE
APFELgui does not compile in version 2.7.0

### ISSUE THREAD

**Issue by badshah400** [scarrazza/apfel#3]
I get failures when building the APFELgui component of APFEL, namely:

    [   96s] src/pdfdialog.cxx: In member function 'void PDFDialog::DIS(double, double, double, double, const string&amp;, const string&amp;, int, const string&amp;, const string&amp;, double*, double*, double*, double*, double*, double*, double*, double*)':
    [   96s] src/pdfdialog.cxx:969:9: error: 'DIS_xsec' is not a member of 'APFEL'
    [   96s]          APFEL::DIS_xsec(x,qi,qf,y,0,proc,scheme,pto,pdfset.toStdString(),irep,
    [   96s]          ^
    [   96s] src/pdfdialog.cxx:980:9: error: 'DIS_xsec' is not a member of 'APFEL'
    [   96s]          APFEL::DIS_xsec(x,qi,qf,y,0,proc,scheme,pto,pdfset.toStdString(),0,
    [   96s]          ^
    [   96s] src/pdfdialog.cxx:994:13: error: 'DIS_xsec' is not a member of 'APFEL'
    [   96s]              APFEL::DIS_xsec(x,qi,qf,y,0,proc,scheme,pto,pdfset.toStdString(),r+1,
    [   96s]              ^
    [   96s] src/pdfdialog.cxx:1033:9: error: 'DIS_xsec' is not a member of 'APFEL'
    [   96s]          APFEL::DIS_xsec(x,qi,qf,y,0,proc,scheme,pto,pdfset.toStdString(),0,
    [   96s]          ^
    [   96s] src/pdfdialog.cxx:1047:13: error: 'DIS_xsec' is not a member of 'APFEL'
    [   96s]              APFEL::DIS_xsec(x,qi,qf,y,0,proc,scheme,pto,pdfset.toStdString(),r+1,
    [   96s]              ^
    [   96s] src/pdfdialog.cxx:1091:13: error: 'DIS_xsec' is not a member of 'APFEL'
    [   96s]              APFEL::DIS_xsec(x,qi,qf,y,0,proc,scheme,pto,pdfset.toStdString(),r+1,
    [   96s]              ^
    [   97s] Makefile:321: recipe for target 'src/pdfdialog.o' failed
    [   97s] make: *** [src/pdfdialog.o] Error 1
    [   97s] make: *** Waiting for unfinished jobs....

Would be very grateful if you could take a look at this and let me know if I am doing something wrong or suggest how to fix it. Thanks for your great software

**Comment by scarrazza** [comment]
Thanks for reporting this issue. APFEL GUI is superseded by APFEL Web (http://apfel.mi.infn.it/), so it is not supported any longer and will be removed from the repository soon.
